name: Auto down deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - '**'

jobs:
  down:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            nocobase/nocobase
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Down
        uses: appleboy/ssh-action@master
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        with:
          envs: IMAGE_TAG
          script: |
            export APP_NAME=$(echo $IMAGE_TAG | cut -d ":" -f 2)
            echo $APP_NAME
            echo "http://localhost:33000/down/$APP_NAME"
